applications:
  app:
    type: php:8.3

    source:
      root: "/"

    runtime:
      extensions:
        - curl

    web:
      locations:
        "/":
          root: "public"
          index:
            - index.html
          passthru: "/router.php"
          scripts: true
          allow: true
          expires: -1

routes:
  "https://{default}/":
    type: upstream
    upstream: "app:http"